# Generated by Django 3.2.5 on 2022-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word_in_norwgian', models.CharField(max_length=100)),
                ('word_in_polish', models.CharField(max_length=100)),
            ],
        ),
    ]
