# Generated by Django 3.2.5 on 2022-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnNorwegianApp', '0002_vocabulary_word_in_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word_in_english',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
