# Generated by Django 3.2.5 on 2022-04-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnNorwegianApp', '0003_alter_vocabulary_word_in_english'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='word_in_norwgian',
            new_name='word_in_norwegian',
        ),
    ]
