# Generated by Django 3.2.5 on 2022-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnNorwegianApp', '0004_rename_word_in_norwgian_vocabulary_word_in_norwegian'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='category',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_in_english',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_in_norwegian',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_in_polish',
            field=models.CharField(max_length=70),
        ),
    ]
