# Generated by Django 3.2.5 on 2022-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnNorwegianApp', '0006_uregelrette_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word_in_english',
            field=models.CharField(max_length=70),
        ),
    ]
